# Generated by Django 6.1.1 on 2026-09-25 07:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihandler', '0002_appeal_appealhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='management_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jk_users', to='apihandler.managementorganization'),
        ),
        migrations.AlterField(
            model_name='domik',
            name='management_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domiks', to='apihandler.managementorganization'),
        ),
    ]
