# Generated by Django 6.1.1 on 2026-09-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihandler', '0003_managementorganization_user_management_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domik',
            name='management_org',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
