# Generated by Django 6.1.1 on 2026-09-25 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihandler', '0004_alter_domik_management_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domik',
            name='management_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domiks', to='apihandler.managementorganization'),
        ),
    ]
