# Generated by Django 5.2.17 on 2026-09-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apihandler', '0005_alter_domik_management_org'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JKDomik',
        ),
    ]
