# Generated by Django 5.2.17 on 2026-09-26 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihandler', '0007_poll_choice_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalRepair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tariff_per_sqm', models.DecimalField(decimal_places=2, default=0, help_text='Руб. за м² в месяц (справочно, устанавливается регионом)', max_digits=8)),
                ('collected_total', models.DecimalField(decimal_places=2, default=0, help_text='Собрано всего, руб. (УК обновляет вручную)', max_digits=14)),
                ('spent_total', models.DecimalField(decimal_places=2, default=0, help_text='Потрачено всего, руб. (УК обновляет вручную)', max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital_repair', to='apihandler.domik')),
            ],
        ),
        migrations.CreateModel(
            name='CapitalRepairWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_type', models.CharField(max_length=255)),
                ('planned_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В работе'), ('done', 'Выполнено')], default='planned', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contractor', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capital_repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='apihandler.capitalrepair')),
            ],
            options={
                'ordering': ['planned_year', 'work_type'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('domik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='apihandler.domik')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
