# Generated by Django 5.2.17 on 2026-09-28 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihandler', '0008_capitalrepair_capitalrepairwork_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_key', to='apihandler.apartment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
