# Generated by Django 5.2.17 on 2026-09-28 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihandler', '0009_apartmentkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentkey',
            name='purpose',
            field=models.CharField(choices=[('bind', 'Привязка'), ('unbind', 'Отвязка')], default='bind', max_length=10),
        ),
        migrations.AlterField(
            model_name='apartmentkey',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_keys', to='apihandler.apartment'),
        ),
        migrations.AlterUniqueTogether(
            name='apartmentkey',
            unique_together={('apartment', 'purpose')},
        ),
    ]
